/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.hugo.atena.view;

import com.hugo.atena.controler.MedicaoGasControler;
import com.hugo.atena.model.Apartamento;
import com.hugo.atena.model.Competencia;
import com.hugo.atena.model.MedicaoGas;
import com.hugo.atena.utils.HNumber;
import com.hugo.atena.view.model.ComboBoxModelApartamento;
import com.hugo.atena.view.model.ComboBoxModelCompetencia;
import java.math.BigDecimal;
import java.math.RoundingMode;
import javax.swing.JOptionPane;

/**
 *
 * @author hugo
 */
public class FormMedicaoGas extends HDialog {
    
    private final MedicaoGasControler controleMedeGas = new MedicaoGasControler();

    /**
     * Creates new form formPeople
     *
     * @param parent
     * @param modal
     */
    public FormMedicaoGas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        painelBotoesManutencao.add(this.getPainelSalvador());
        
        painelListaDados.add(this.getPainelNavegacao(), java.awt.BorderLayout.PAGE_END);
        
        jComboBoxApartamento.setModel(ComboBoxModelApartamento.getModel());
        
        jComboBoxCompetencia.setModel(ComboBoxModelCompetencia.getModel());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane = new javax.swing.JTabbedPane();
        painelListaDados = new javax.swing.JPanel();
        painelCadastro = new javax.swing.JPanel();
        painelCamposPersonaizados = new javax.swing.JPanel();
        jTextFieldLeituraAnterior = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldLeituraAtual = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxApartamento = new javax.swing.JComboBox<>();
        jComboBoxCompetencia = new javax.swing.JComboBox<>();
        jButtonCalculaMedicaoGas = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldConsumoMCubico = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldPrecoMetroCubico = new javax.swing.JTextField();
        jTextFieldValor = new javax.swing.JTextField();
        painelBotoesManutencao = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Pessoas");

        jTabbedPane.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTabbedPaneFocusGained(evt);
            }
        });

        painelListaDados.setLayout(new java.awt.BorderLayout());
        jTabbedPane.addTab("Lista de medições", painelListaDados);

        painelCadastro.setLayout(new java.awt.BorderLayout());

        painelCamposPersonaizados.setPreferredSize(new java.awt.Dimension(694, 350));
        painelCamposPersonaizados.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                painelCamposPersonaizadosFocusGained(evt);
            }
        });

        jTextFieldLeituraAnterior.setEnabled(false);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Leitura anterior:");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Leitura atual:");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Apartamento:");

        jLabel1.setText("Competencia:");

        jComboBoxApartamento.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxApartamentoItemStateChanged(evt);
            }
        });
        jComboBoxApartamento.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jComboBoxApartamentoInputMethodTextChanged(evt);
            }
        });

        jComboBoxCompetencia.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxCompetenciaItemStateChanged(evt);
            }
        });

        jButtonCalculaMedicaoGas.setText("Calcular");
        jButtonCalculaMedicaoGas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalculaMedicaoGasActionPerformed(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Preço M³:");

        jTextFieldConsumoMCubico.setEnabled(false);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Consumo M³:");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Valor:");

        jTextFieldPrecoMetroCubico.setEnabled(false);

        jTextFieldValor.setEnabled(false);

        javax.swing.GroupLayout painelCamposPersonaizadosLayout = new javax.swing.GroupLayout(painelCamposPersonaizados);
        painelCamposPersonaizados.setLayout(painelCamposPersonaizadosLayout);
        painelCamposPersonaizadosLayout.setHorizontalGroup(
            painelCamposPersonaizadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCamposPersonaizadosLayout.createSequentialGroup()
                .addGroup(painelCamposPersonaizadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelCamposPersonaizadosLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxApartamento, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelCamposPersonaizadosLayout.createSequentialGroup()
                        .addGroup(painelCamposPersonaizadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(painelCamposPersonaizadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelCamposPersonaizadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelCamposPersonaizadosLayout.createSequentialGroup()
                                .addGroup(painelCamposPersonaizadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldConsumoMCubico)
                                    .addComponent(jTextFieldPrecoMetroCubico)
                                    .addComponent(jTextFieldValor)
                                    .addComponent(jTextFieldLeituraAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldLeituraAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jButtonCalculaMedicaoGas, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jComboBoxCompetencia, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 52, Short.MAX_VALUE))
        );
        painelCamposPersonaizadosLayout.setVerticalGroup(
            painelCamposPersonaizadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelCamposPersonaizadosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelCamposPersonaizadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxApartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCamposPersonaizadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxCompetencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCamposPersonaizadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldLeituraAtual)
                    .addComponent(jButtonCalculaMedicaoGas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCamposPersonaizadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldLeituraAnterior)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCamposPersonaizadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldConsumoMCubico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCamposPersonaizadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPrecoMetroCubico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelCamposPersonaizadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap())
        );

        painelCadastro.add(painelCamposPersonaizados, java.awt.BorderLayout.NORTH);

        painelBotoesManutencao.setLayout(new java.awt.GridLayout(1, 0));
        painelCadastro.add(painelBotoesManutencao, java.awt.BorderLayout.SOUTH);

        jTabbedPane.addTab("Medição gás", painelCadastro);

        getContentPane().add(jTabbedPane, java.awt.BorderLayout.PAGE_START);

        setSize(new java.awt.Dimension(724, 523));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void jTabbedPaneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTabbedPaneFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPaneFocusGained

    private void painelCamposPersonaizadosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_painelCamposPersonaizadosFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_painelCamposPersonaizadosFocusGained

    private void jButtonCalculaMedicaoGasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalculaMedicaoGasActionPerformed
        // TODO add your handling code here:
        try {
            
            if (!HNumber.isInteger(jTextFieldLeituraAtual.getText())) {
                JOptionPane.showMessageDialog(this, "É obrigatório informar a leitura atual.");
                return;
            }
            
            if (!HNumber.isInteger(jTextFieldLeituraAnterior.getText())) {
                JOptionPane.showMessageDialog(this, "É obrigatório informar o apartamento "
                        + "e a competência, antes de realizar o cálculo.");
                return;
            }
            
            int gasAnterior = Integer.parseInt(jTextFieldLeituraAnterior.getText());

            //Criar método para buscar úlitmo lancamento
            double valorBotijao = 308;
            double metroCubicoP13 = 18;
            double valorMCubico = (valorBotijao / metroCubicoP13);
            
            int gasAtual = Integer.parseInt(jTextFieldLeituraAtual.getText());
            
            int consumo = gasAtual - gasAnterior;
            
            double valorDevido = consumo * (valorMCubico / 1000);
            
            BigDecimal valorDevidoBD = new BigDecimal(valorDevido).setScale(2, RoundingMode.HALF_EVEN);
            BigDecimal valorMCubicoBD = new BigDecimal(valorMCubico).setScale(2, RoundingMode.HALF_EVEN);
            
            this.jTextFieldPrecoMetroCubico.setText(valorMCubicoBD.toString());
            this.jTextFieldConsumoMCubico.setText(String.valueOf(consumo));
            this.jTextFieldLeituraAnterior.setText(String.valueOf(gasAnterior));
            this.jTextFieldValor.setText(valorDevidoBD.toString());
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
        

    }//GEN-LAST:event_jButtonCalculaMedicaoGasActionPerformed
    
    private void alimentaLeituraAnterior() {

        //verifica se os dois combos estão preenchidos, se tiver busca...
        if (jComboBoxApartamento.getModel().getSelectedItem() != null
                && jComboBoxCompetencia.getModel().getSelectedItem() != null) {
            
            Apartamento a = (Apartamento) jComboBoxApartamento.getModel().getSelectedItem();
            Competencia c = (Competencia) jComboBoxCompetencia.getModel().getSelectedItem();
            
            if (a.getId() > 0 && c.getId() > 0) {
                
                int gasAnterior = getControler().getUltimaMedicaoGas(a, c);
                this.jTextFieldLeituraAnterior.setText(String.valueOf(gasAnterior));
            }
            
        }
    }
    

    private void jComboBoxApartamentoInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jComboBoxApartamentoInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxApartamentoInputMethodTextChanged

    private void jComboBoxApartamentoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxApartamentoItemStateChanged
        // TODO add your handling code here:
        alimentaLeituraAnterior();
    }//GEN-LAST:event_jComboBoxApartamentoItemStateChanged

    private void jComboBoxCompetenciaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxCompetenciaItemStateChanged
        // TODO add your handling code here:
        alimentaLeituraAnterior();
    }//GEN-LAST:event_jComboBoxCompetenciaItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMedicaoGas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMedicaoGas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMedicaoGas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMedicaoGas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormMedicaoGas dialog = new FormMedicaoGas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCalculaMedicaoGas;
    private javax.swing.JComboBox<String> jComboBoxApartamento;
    private javax.swing.JComboBox<String> jComboBoxCompetencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTextField jTextFieldConsumoMCubico;
    private javax.swing.JTextField jTextFieldLeituraAnterior;
    private javax.swing.JTextField jTextFieldLeituraAtual;
    private javax.swing.JTextField jTextFieldPrecoMetroCubico;
    private javax.swing.JTextField jTextFieldValor;
    private javax.swing.JPanel painelBotoesManutencao;
    private javax.swing.JPanel painelCadastro;
    private javax.swing.JPanel painelCamposPersonaizados;
    private javax.swing.JPanel painelListaDados;
    // End of variables declaration//GEN-END:variables

    @Override
    public void habilitarTextField(boolean habilitar) {
        
        jComboBoxApartamento.setEnabled(habilitar);
        jComboBoxCompetencia.setEnabled(habilitar);
        jTextFieldLeituraAtual.setEnabled(habilitar);
        jButtonCalculaMedicaoGas.setEnabled(habilitar);
        
    }
    
    @Override
    public void limparTextField() {
        
        jComboBoxApartamento.getModel().setSelectedItem(new Apartamento());
        jComboBoxCompetencia.getModel().setSelectedItem(new Competencia());
        
        jTextFieldLeituraAtual.setText("");
        jTextFieldLeituraAnterior.setText("");
        jTextFieldConsumoMCubico.setText("");
        jTextFieldPrecoMetroCubico.setText("");
        jTextFieldValor.setText("");
        
    }
    
    @Override
    public void preencherTextField(Object object) {
        
        MedicaoGas medicaoGas = (MedicaoGas) object;
        
        jComboBoxApartamento.getModel().setSelectedItem(medicaoGas.getApartamento());
        jComboBoxCompetencia.getModel().setSelectedItem(medicaoGas.getCompetencia());
        
        jTextFieldLeituraAtual.setText(String.valueOf(medicaoGas.getLeituraAtual()));
        jTextFieldLeituraAnterior.setText(String.valueOf(medicaoGas.getLeituraAnterior()));
        jTextFieldConsumoMCubico.setText(String.valueOf(medicaoGas.getTotalConsumido()));
        jTextFieldPrecoMetroCubico.setText(String.valueOf(medicaoGas.getPrecoMetroCubico()));
        jTextFieldValor.setText(String.valueOf(medicaoGas.getValor()));
    }
    
    @Override
    public Object getValoresInformadosNaTela() {
        
        MedicaoGas medicaoGas = (MedicaoGas) controleMedeGas.getEntity();
        
        medicaoGas.setApartamento((Apartamento) jComboBoxApartamento.getModel().getSelectedItem());
        medicaoGas.setCompetencia((Competencia) jComboBoxCompetencia.getModel().getSelectedItem());
        
        medicaoGas.setLeituraAtual(Integer.parseInt(jTextFieldLeituraAtual.getText()));
        medicaoGas.setLeituraAnterior(Integer.parseInt(jTextFieldLeituraAnterior.getText()));
        medicaoGas.setTotalConsumido(Integer.parseInt(jTextFieldConsumoMCubico.getText()));
        medicaoGas.setPrecoMetroCubico(Double.parseDouble(jTextFieldPrecoMetroCubico.getText()));
        medicaoGas.setValor(Double.parseDouble(jTextFieldValor.getText()));
        
        return medicaoGas;
        
    }
    
    @Override
    public MedicaoGasControler getControler() {
        return this.controleMedeGas;
    }
    
    @Override
    public void atualizaValoresDadosTela() {
        
        preencherTextField((MedicaoGas) controleMedeGas.getEntity());
    }
}
